import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Script from "next/script";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Resort Collection",
  description: "Generated by BookinGuru",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
        <iframe
          id="widget-f9e99163"
          src="https://demo.d229envuj1hcw.amplifyapp.com/brand/widgets/embed?iframeCode=widget-f9e99163"
          style={{
            position: "fixed",
            width: 360,
            height: 200,
            bottom: 20,
            right: 20,
            opacity: 0,
          }}
        />
        <Script src="/widget-triggers.js" strategy="afterInteractive" />
      </body>
    </html>
  );
}
